### ISSUE TITLE
Idea: Consider scaffolding Grains/Interface projects?

### ISSUE THREAD

**Issue by ry8806** [thiagoloureiro/OrleansSiloNetCoreProjectTemplate#1]
Hey,

Thanks for the template - just wondering if you've considered scaffolding the Grains/Interface projects too - these could be empty or include a quick/simple "HelloWorld" sample?

**Comment by thiagoloureiro** [comment]
@ry8806 Yes, Im planning to create this ones:

- SiloHost with SQL (To save to OrleansMembershipTable)
- Interface
- Grains
- Interface + Grains
- ClientAPI (WebAPI Client Implementation)
- ClientConsole (Console App Implementation)

If you have any ideas or suggestions please let me know, i'll keep it here open.

**Comment by thiagoloureiro** [comment]
Created Grain and Interface Templates:

https://github.com/thiagoloureiro/OrleansGrainNetStandardProjectTemplate

https://github.com/thiagoloureiro/OrleansInterfaceNetStandardProjectTemplate
